# Generated by Django 2.2.7 on 2019-12-06 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Cargo: ')),
                ('eh_chefe', models.BooleanField(default=False)),
                ('eh_motorista', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Departamento: ')),
                ('cod', models.CharField(blank=True, max_length=60, null=True, verbose_name='Codigo do Departamento: ')),
                ('eh_transporte', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome: ')),
                ('matricula', models.CharField(blank=True, max_length=14, null=True, verbose_name='Matricula: ')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_g2.Cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_g2.Departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(blank=True, max_length=60, null=True, verbose_name='Veículo: ')),
                ('placa', models.CharField(blank=True, max_length=6, null=True, verbose_name='Placa: ')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(blank=True, max_length=25, null=True, verbose_name='Origem: ')),
                ('destino', models.CharField(blank=True, max_length=25, null=True, verbose_name='Destino: ')),
                ('qtdPessoas', models.CharField(blank=True, max_length=1, null=True, verbose_name='Quantidade de Pessoas: ')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora: ')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_g2.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_g2.Funcionario')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_g2.Solicitacoes')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_g2.Veiculos')),
            ],
        ),
    ]
