# Generated by Django 2.2.7 on 2019-12-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_g2', '0002_auto_20191208_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='eh_chefe',
            field=models.BooleanField(default=False, verbose_name='É chefe do departamento de viagens?: '),
        ),
    ]
