# Generated by Django 2.2.7 on 2019-12-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_g2', '0003_auto_20191209_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora: '),
        ),
    ]
